



# link
# sudo ln -s /System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport /usr/sbin/airport
if [ -f ~/Documents/google_drive/code/dot-files/bash/bash_aliases ]
then
 . ~/Documents/google_drive/code/dot-files/bash/bash_aliases
fi
if [ -f ~/Documents/google_drive/code/dot-files/bash/bash_funcs ]
then
  . ~/Documents/google_drive/code/dot-files/bash/bash_funcs
fi
export ANDROID_TOOLS_PATH="~/Documents/projects/everythingelse/android/android-sdk-macosx"
export NODE_PATH="/usr/local/lib/node"
export PATH=$ANDROID_TOOLS_PATH/platform-tools:$ANDROID_TOOLS_PATH/tools:/usr/local/bin:/usr/local/sbin:~/bin:~/bin/scripts:~/Documents/projects/javascript/less.js/bin:$PATH

export EDITOR=nano
export LS_COLORS='di=01;33'
